export {
  ApiClient,
  apiClient,
  setAuthToken,
  getAuthToken,
  AUTH_EXPIRED_EVENT,
} from './client.ts'
export { ApiError, toApiError, type ApiErrorCode } from './errors.ts'
export type {
  AdminBookingsQuery,
  AdminService,
  ApiProductDto,
  AuthService,
  CreateOrderItem,
  CreateOrderRequest,
  CreateOrderResponse,
  LoginRequest,
  LoginResponse,
  OrderAdminService,
  OrdersService,
  ProductCreatePayload,
  ProductService,
  RegisterRequest,
  SetUserActiveRequest,
  StaffRole,
  SearchService,
  SearchTicketsQuery,
  TripsQuery,
  TripsService,
} from './contracts.ts'
export {
  adminService,
  authService,
  ordersService,
  searchService,
  tripsService,
  productService,
  orderAdminService,
  deleteUser,
  setUserRole,
  setUserActive,
} from './services/index.ts'
